services:
  - type: web
    name: file-processor-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: API_KEY
        value: your_api_key_here
